'use strict';
const APP_VERSION='1.3.0';
const PROGRAM={
A:[
{name:'Împins la piept la aparat',kg:30,step:5,sets:3,min:8,max:12,rest:120,video:'machine chest press proper form'},
{name:'Tracțiuni la helcometru - priză neutră',kg:40,step:5,sets:3,min:8,max:12,rest:120,video:'neutral grip lat pulldown proper form'},
{name:'Împins înclinat cu gantere',kg:12,step:2,sets:3,min:8,max:12,rest:120,video:'incline dumbbell press proper form'},
{name:'Ramat la cablu din șezut',kg:35,step:5,sets:3,min:8,max:12,rest:120,video:'seated cable row proper form'},
{name:'Flexii biceps cu gantere',kg:12,step:2,sets:3,min:10,max:15,rest:75,video:'dumbbell biceps curl proper form'},
{name:'Extensii triceps cu frânghia',kg:20,step:5,sets:3,min:10,max:15,rest:75,video:'rope triceps pushdown proper form'}],
B:[
{name:'Presa pentru umeri la aparat',kg:25,step:5,sets:3,min:8,max:12,rest:120,video:'machine shoulder press proper form'},
{name:'Ramat cu pieptul sprijinit',kg:60,step:5,sets:3,min:8,max:12,rest:120,video:'seated chest supported row machine proper form'},
{name:'Ridicări laterale cu gantere',kg:5,step:1,sets:3,min:12,max:15,rest:75,video:'dumbbell lateral raise proper form'},
{name:'Face pull la cablu',kg:15,step:5,sets:3,min:12,max:15,rest:75,video:'face pull cable proper form'},
{name:'Ridicări din umeri pentru trapez',kg:20,step:2,sets:3,min:10,max:15,rest:90,video:'dumbbell shrug proper form'},
{name:'Presa pentru picioare - întreținere',kg:110,step:10,sets:2,min:10,max:15,rest:120,video:'leg press proper form'},
{name:'Flexii femurali la aparat - întreținere',kg:60,step:5,sets:2,min:10,max:15,rest:90,video:'leg curl machine proper form'}],
C:[
{name:'Fluturări la aparat pentru piept',kg:35,step:5,sets:3,min:10,max:15,rest:90,video:'pec deck fly proper form'},
{name:'Tracțiuni la helcometru - priză medie',kg:40,step:5,sets:3,min:8,max:12,rest:120,video:'lat pulldown proper form'},
{name:'Împins la piept - varianta alternativă',kg:35,step:5,sets:3,min:8,max:12,rest:120,video:'converging chest press proper form'},
{name:'Ramat jos la aparat',kg:45,step:5,sets:3,min:8,max:12,rest:120,video:'low row machine proper form'},
{name:'Ridicări laterale la cablu',side:'STÂNGA',kg:5,step:2.5,sets:3,min:10,max:15,rest:75,video:'cable lateral raise proper form'},
{name:'Ridicări laterale la cablu',side:'DREAPTA',kg:5,step:2.5,sets:3,min:10,max:15,rest:75,video:'cable lateral raise proper form'},
{name:'Flexii ciocan',kg:10,step:2,sets:3,min:10,max:15,rest:75,video:'hammer curl proper form'},
{name:'Extensii triceps deasupra capului cu frânghia',kg:12.5,step:2.5,sets:3,min:10,max:15,rest:75,video:'overhead rope triceps extension proper form'},
{name:'Pallof press',side:'STÂNGA',kg:40,step:5,sets:2,min:10,max:12,rest:60,video:'pallof press proper form'},
{name:'Pallof press',side:'DREAPTA',kg:40,step:5,sets:2,min:10,max:12,rest:60,video:'pallof press proper form'}]};
const NEXT={A:'B',B:'C',C:'A'},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let currentDay=localStorage.getItem('fitDay')||'B',timerId=null,waitingWorker=null,installPrompt=null,startupUpdatePhase=true;
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function sessionKey(day=currentDay,date=localDate()){return `fit:${date}:${day}`}
function loadSession(day=currentDay,date=localDate()){try{return JSON.parse(localStorage.getItem(sessionKey(day,date))||'{}')}catch{return {}}}
function saveSession(data,day=currentDay,date=localDate()){localStorage.setItem(sessionKey(day,date),JSON.stringify(data));showToast('Salvat');updateStats()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function requiredFields(ex){return ex.sets===2?['s2','s3']:['s1','s2','s3']}
function repsAverage(row,ex){const values=requiredFields(ex).map(k=>parseInt(row?.[k],10)).filter(Number.isFinite);return values.length===requiredFields(ex).length?values.reduce((a,b)=>a+b,0)/values.length:null}
function hasAnyReps(row,ex){return requiredFields(ex).some(k=>String(row?.[k]??'').trim())}
function isComplete(row,ex){return requiredFields(ex).every(k=>parseInt(row?.[k],10)>0)}
function classFor(row,ex){if(row?.done||isComplete(row,ex))return'done';if(hasAnyReps(row,ex))return'partial';return''}
function setValue(row,ex,n){if(ex.sets===2&&n===1)return'X';return row?.[`s${n}`]??''}
function historyFor(day){const out=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i),m=key?.match(/^fit:(\d{4}-\d{2}-\d{2}):([ABC])$/);if(m&&m[2]===day&&m[1]!==localDate())out.push({date:m[1],data:loadSession(day,m[1])})}return out.sort((a,b)=>b.date.localeCompare(a.date))}
function prescription(day,index,ex){const last=historyFor(day)[0],row=last?.data?.[index];if(!row)return{kg:ex.kg,last:null,medal:false};const kg=parseFloat(row.kg??ex.kg)||ex.kg,avg=repsAverage(row,ex);return{kg:avg!==null&&avg>12?kg+ex.step:kg,last:row,medal:avg!==null&&avg>12,lastAvg:avg}}
function award(row,ex,p){if(p.medal)return{icon:'🏅',text:`Masă crescută: media anterioară ${p.lastAvg.toFixed(1)} repetări.`};const avg=repsAverage(row,ex),prev=p.last?repsAverage(p.last,ex):null,same=Number(row?.kg??p.kg)===Number(p.last?.kg??p.kg);if(avg!==null&&prev!==null&&same&&avg>prev)return{icon:'⭐',text:`Record de repetări: media ${avg.toFixed(1)}, înainte ${prev.toFixed(1)}.`};return null}
function render(){localStorage.setItem('fitDay',currentDay);$$('.tab').forEach(b=>b.classList.toggle('on',b.dataset.d===currentDay));$('#day').textContent=currentDay;const data=loadSession();const exercises=PROGRAM[currentDay].map((ex,index)=>{const row=data[index]||{},p=prescription(currentDay,index,ex);if(row.kg==null)row.kg=p.kg;const done=row.done||isComplete(row,ex),prize=award(row,ex,p);return `<article class="ex ${classFor(row,ex)}" data-i="${index}"><div class="head"><div class="nr">${index+1}</div><div class="wrap"><div class="name">${esc(ex.name)}</div>${ex.side?`<div class="side">${esc(ex.side)}</div>`:''}</div><a class="video" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${encodeURIComponent(ex.video)}">VIDEO ▶</a></div><div class="meta"><span class="pill">${ex.sets} seturi</span><span class="pill">${ex.min}–${ex.max} repetări</span><span class="pill">${ex.rest} sec pauză</span></div>${prize?`<div class="award"><b>${prize.icon}</b><span>${esc(prize.text)}</span></div>`:`<div class="dec">Media ultimei ședințe ${p.lastAvg==null?'nu există':p.lastAvg.toFixed(1)} — ${p.medal?'creștem':'menținem'} masa.</div>`}<div class="grid"><div class="field"><label>KG</label><input data-f="kg" inputmode="decimal" value="${esc(row.kg)}"></div>${[1,2,3].map(n=>`<div class="field"><label>SET ${n}</label><input data-f="s${n}" inputmode="numeric" value="${esc(setValue(row,ex,n))}" ${ex.sets===2&&n===1?'disabled':''}></div>`).join('')}</div><div class="timer-row"><button class="timer" data-t="${ex.rest}">⏱ ${ex.rest}s</button></div><textarea class="notes" data-f="note" placeholder="Observații...">${esc(row.note||'')}</textarea><button class="donebtn ${done?'on':''}" data-done>${done?'✓ FINALIZAT':'MARCAJ FINALIZAT'}</button></article>`}).join('');
const optional=`<article class="optional-card"><div class="optional-head"><div class="nr">+</div><div><div class="name">OPTIONAL LA FINAL</div><div class="optional-sub">Completezi numai când mai faci ceva după programul principal.</div></div></div><textarea class="optional-notes" id="optional" placeholder="Ex.: bandă 10 min; eliptică 12 min; abdomen pe minge 3 × 15...">${esc(data.optional||'')}</textarea></article>`;$('#list').innerHTML=exercises+optional;
$$('.ex').forEach(card=>{const index=Number(card.dataset.i);card.querySelectorAll('[data-f]').forEach(el=>{const persist=()=>{const d=loadSession();d[index]={...(d[index]||{}),[el.dataset.f]:el.value};saveSession(d);render()};el.addEventListener('change',persist);if(el.tagName==='TEXTAREA')el.addEventListener('blur',persist)});card.querySelector('[data-done]').addEventListener('click',()=>{const d=loadSession();d[index]={...(d[index]||{}),done:!(d[index]?.done||isComplete(d[index],PROGRAM[currentDay][index]))};saveSession(d);render()});card.querySelector('[data-t]').addEventListener('click',e=>startTimer(Number(e.currentTarget.dataset.t),e.currentTarget))});$('#optional').addEventListener('change',e=>{const d=loadSession();d.optional=e.currentTarget.value;saveSession(d)});updateStats()}
function updateStats(){const data=loadSession();let done=0,volume=0;PROGRAM[currentDay].forEach((ex,i)=>{const r=data[i]||{};if(r.done||isComplete(r,ex))done++;const reps=[r.s1,r.s2,r.s3].reduce((s,v)=>s+(parseInt(v,10)||0),0);volume+=(parseFloat(r.kg??prescription(currentDay,i,ex).kg)||0)*reps});$('#prog').textContent=`${done}/${PROGRAM[currentDay].length}`;$('#vol').textContent=Math.round(volume).toLocaleString('ro-RO')}
function startTimer(seconds,button){clearInterval(timerId);const end=Date.now()+seconds*1000,original=`⏱ ${seconds}s`;timerId=setInterval(()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));button.textContent=left?`⏱ ${left}s`:'GATA!';if(!left){clearInterval(timerId);navigator.vibrate?.([200,120,200]);setTimeout(()=>button.textContent=original,1500)}},250)}
function sessionText(day,data,date){const lines=[`SALA FIT - ${date} - ZIUA ${day}`];PROGRAM[day].forEach((ex,i)=>{const r=data[i]||{};lines.push(`${i+1}. ${ex.name}${ex.side?' '+ex.side:''} | ${r.kg??ex.kg} kg | ${ex.sets===2?'X/':''}${ex.sets===2?(r.s2||'')+'/'+(r.s3||''):(r.s1||'')+'/'+(r.s2||'')+'/'+(r.s3||'')}${r.note?' | '+r.note:''}`)});lines.push(`OPTIONAL: ${String(data.optional||'').trim()||'nimic'}`);return lines.join('\n')}
function quoteCsv(v){return `"${String(v??'').replaceAll('"','""')}"`}
function createCsv(day,data,date){const rows=[['Data','Zi','Ordine','Exercitiu','Parte','Kg','Set 1','Set 2','Set 3','Media repetitii','Finalizat','Observatii']];PROGRAM[day].forEach((ex,i)=>{const r=data[i]||{},avg=repsAverage(r,ex);rows.push([date,day,i+1,ex.name,ex.side||'Bilateral',r.kg??ex.kg,ex.sets===2?'X':r.s1||'',r.s2||'',r.s3||'',avg==null?'':avg.toFixed(2),r.done||isComplete(r,ex)?'DA':'NU',r.note||''])});rows.push([date,day,'OPTIONAL','OPTIONAL','','','','','','','',data.optional||'']);return '\ufeff'+rows.map(r=>r.map(quoteCsv).join(';')).join('\r\n')}
async function shareCsv(day,data,date){const name=`SALA_${date}_${day}.csv`,file=new File([createCsv(day,data,date)],name,{type:'text/csv;charset=utf-8'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({title:`SALA FIT ${day}`,text:`Ședința ${day} din ${date}`,files:[file]});showToast('Trimis către Drive');return}}catch(e){if(e?.name==='AbortError'){showToast('Partajare anulată');return}}const url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1500);showToast('CSV descărcat')}
async function finishSession(){const button=$('#finish');if(button.classList.contains('busy'))return;button.classList.add('busy');const day=currentDay,date=localDate(),data=loadSession(day,date);PROGRAM[day].forEach((ex,i)=>data[i]={...(data[i]||{}),done:isComplete(data[i]||{},ex)||data[i]?.done===true});localStorage.setItem(sessionKey(day,date),JSON.stringify(data));localStorage.setItem('fitLastFinished',JSON.stringify({day,date,at:new Date().toISOString()}));currentDay=NEXT[day];localStorage.setItem('fitDay',currentDay);render();showToast(`Gata ${day} → urmează ${currentDay}`);button.classList.remove('busy');await new Promise(r=>setTimeout(r,250));await shareCsv(day,data,date)}
function showToast(message='Salvat'){const t=$('#toast');t.textContent=message;t.classList.add('on');clearTimeout(showToast.id);showToast.id=setTimeout(()=>t.classList.remove('on'),1800)}
function resetCurrent(){if(!confirm(`Ștergi valorile introduse astăzi pentru ziua ${currentDay}?`))return;localStorage.removeItem(sessionKey());render();showToast('Resetat')}
$$('.tab').forEach(b=>b.addEventListener('click',()=>{currentDay=b.dataset.d;render()}));$('#reset').addEventListener('click',resetCurrent);$('#copy').addEventListener('click',async()=>{await navigator.clipboard.writeText(sessionText(currentDay,loadSession(),localDate()));showToast('Copiat')});$('#finish').addEventListener('click',finishSession);$('#version').textContent=`Versiunea ${APP_VERSION}`;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').classList.add('on')});$('#install').addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install').classList.remove('on')});window.addEventListener('appinstalled',()=>showToast('Aplicația a fost instalată'));
function activateUpdate(worker){waitingWorker=worker;worker?.postMessage({type:'SKIP_WAITING'})}function offerUpdate(worker){waitingWorker=worker;if(startupUpdatePhase)activateUpdate(worker);else $('#update').classList.add('on')}$('#applyUpdate').addEventListener('click',()=>waitingWorker?activateUpdate(waitingWorker):location.reload());if('serviceWorker'in navigator){window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});if(reg.waiting)offerUpdate(reg.waiting);reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)offerUpdate(w)})});await reg.update();setTimeout(()=>startupUpdatePhase=false,10000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')reg.update()});setInterval(()=>reg.update(),3600000)}catch(e){startupUpdatePhase=false;console.warn('Actualizarea automată nu a putut fi verificată.',e)}});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}
if(!localStorage.getItem('fitPwaMigrated')){localStorage.setItem('fitPwaMigrated',APP_VERSION);localStorage.setItem('fitDay','B');currentDay='B'}localStorage.setItem('fitAppVersion',APP_VERSION);render();